### ISSUE TITLE
Growtri registration Issue

### ISSUE THREAD

**Issue by DaveEade49** [IATI/ckanext-iati#402]
We've had a ticket through from the above organisation who tried to register via registry but when the log in - the get an error message "Internal Server Error" - when I search for the user I get the same thing.
I also tried to register them as new via Publisher, but got a message saying the "email already exists"

The email is niko@growtri.io

I was wondering if you or one of your devs could take a look?

I also tried to register for them - and the screenshot below shows username not available, but when I search for that username I get the Internal Server Error.

![image](https://github.com/IATI/ckanext-iati/assets/110898894/6e79e18c-3bfb-4d3d-a445-0d2b38814782)

![image](https://github.com/IATI/ckanext-iati/assets/110898894/cbae82fb-d0fa-42a7-8867-d4399929747e)

High

**Comment by cormachallinanderilinx** [comment]
On first look it seems there is an ecoding issue with the username when I visit: https://www.iatiregistry.org/user/growtri 

`ERROR [ckan.config.middleware.flask_app] 'ascii' codec can't encode character u'\u0304' in position 16: ordinal not in range(128)
Traceback (most recent call last):
 File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/lib/ckan/default/src/ckan/ckan/views/user.py", line 148, in read
extra_vars = _extra_template_variables(context, data_dict)
 File "/usr/lib/ckan/default/src/ckan/ckan/views/user.py", line 58, in _extra_template_variables
user_dict = logic.get_action(u'user_show')(context, data_dict)
File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
result = _action(context, data_dict, **kw)
File "/usr/lib/ckan-extensions/ckanext-iati/ckanext/iati/logic/action.py", line 602, in user_show
user_dict = get_core.user_show(context, data_dict)
File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py", line 1447, in user_show
 user_obj, context, include_password_hash, include_plugin_extras)
File "/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 543, in user_dictize
qualified=True
File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 506, in url_for_static
return url_for_static_or_external(*args, **kw)
File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 524, in url_for_static_or_external
is_external, fixed_url = fix_arg(args[0])
File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 515, in fix_arg
url = urlparse(str(arg))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0304' in position 16: ordinal not in range(128)`

This can be caused from soemthing like using an non-english keyboard or character.

Will continue how best to handle this

**Comment by DaveEade49** [comment]
Ok, thanks Cormac - can we edit in the back-end?

**Comment by cormachallinanderilinx** [comment]
spent some time to test and reproduce on staging.
As a fix I removed the image from the db and seems to be working now: https://www.iatiregistry.org/user/growtri

When re-uploading an image try to not use unicode characters.
The last image uploaded was called "TRī logo.png"

**Comment by DaveEade49** [comment]
Thanks Cormac - that sorts the user out - what about the organisation?
________________________________

**Comment by cormachallinanderilinx** [comment]
From looking around, there is no publisher registered to the email niko@growtri.io

They should be able to create a new publisher through the UI using the 'Add Publisher' button: https://iatiregistry.org/publisher/ 
Then set Contact Email as: niko@growtri.io

If this seems incorrect please send me on the publisher id and name so I can further troubleshoot
